<?php
/**
 * @file
 * Code for the Stanford VPGE Fellowships feature.
 */

define('VPGE_FELLOWSHIPS_MENU_NAME', 'menu-fellowships-funding');
include_once 'stanford_vpge_fellowships.features.inc';

/**
 * Implments hook_views_api
 * @return array
 */
function stanford_subsites_views_api() {
  return array("version" => "3.0");
}


/**
 * Implements hook_view_mode_page_pre_entity_view()
 *
 * Takes over the menu system and triggers context to behave with the node_type
 * context option.
 */
function stanford_vpge_fellowships_view_mode_page_pre_entity_view($entities, $entity_type, $view_mode, $url_pattern) {

  if ($entity_type == "node" && module_exists('context')) {
    $node = $entities[0];
    context_node_condition($node, 'view');
  }

  return $entities;
}

/**
 * Implements hook_view_mode_page_post_entity_view();
 *
 * We take over the menu path in pre_entity_view so we now have to return it
 * back to its original onwer in its original state. We don't want any extra
 * fees for scratch marks.
 */
function stanford_vpge_fellowships_view_mode_page_post_entity_view($entity, $view, $entity_type, $content_type, $view_mode, $pattern) {
  // if ($entity_type == "node" && module_exists('context')) {
  //   $path = current_path();
  //   $menu_item = menu_get_item($path);
  //   menu_set_item(NULL, $menu_item);
  // }
}

/**
 * Add all new fellowship nodes to the fellowship menu along with their view
 * modes.
 */
function stanford_vpge_fellowships_node_insert($node) {

  // Go away if not a fellowship type.
  if ($node->type !== 'fellowship_funding') {
    return;
  }

  $menu = _stanford_vpge_fellowships_get_fellowship_menu();

  // Ensure that the menu exists.
  if (empty($menu)) {
    watchdog('stanford_vpge_fellowships', 'Fellows Menu Is Missing. Could not add new fellowship node to menu.');
    drupal_set_message(t('Error adding fellowship node to menu.'), 'error');
    return;
  }

  // Try to get alias if pathauto is available.
  $path = 'node/' . $node->nid;
  if (module_exists('pathauto')) {
    // pathauto_entity_presave();
    pathauto_node_insert($node);
    $path = drupal_get_path_alias($path);
  }

  $link = array();
  $link['link_path'] = drupal_get_normal_path('node/' . $node->nid);
  $link['link_title'] = $node->title;
  $link['menu_name'] = VPGE_FELLOWSHIPS_MENU_NAME;
  $parent = menu_link_save($link);

  // Create overview link.
  $link = array();
  $link['plid'] = $parent;
  $link['link_path'] = drupal_get_normal_path('node/' . $node->nid);
  $link['menu_name'] = VPGE_FELLOWSHIPS_MENU_NAME;
  $link['link_title'] = t("Overview");
  $link['weight'] = -10;
  menu_link_save($link);

  // Details View Mode.
  $link = array();
  $link['link_path'] = $path . "/details";
  $link['link_title'] = t("Details");
  $link['plid'] = $parent;
  $link['menu_name'] = VPGE_FELLOWSHIPS_MENU_NAME;
  $link['weight'] = -9;
  menu_link_save($link);

  // Create a default context for the fellowship.
  _create_active_fellowship_context($node);

}

/**
 * Create active fellowship context
 * @param   $node the fully saved and/or loaded subsite node object
 * @param   $args a misc array of arguments to pass in
 */

function _create_active_fellowship_context($node, $args) {

  $filter = array(' ' => '-', '/' => '-', '[' => '-', ']' => '-');
  $context_name = strtolower(drupal_clean_css_identifier($node->title, $filter));
  $context_name = substr($context_name, 0, 32);

  $context = new stdClass();
  $context->name = $context_name;
  $context->description = "Active Fellowship: " . $node->title;
  $context->tag = "Fellowships & Funding";
  $context->conditions = array(
    'active_fellowships' => array(
      'values' => array(
        $node->nid => $node->nid,
      ),
    ),
  );

  // if ($theme_region) {
  //   $context->reactions = array(
  //     'block' => array(
  //       'blocks' => array(
  //         "menu_block-" . $delta => array(
  //           'module' => "menu_block",
  //           'delta' => $delta,
  //           'region' => $theme_region,
  //           'weight' => -10,
  //         ),
  //       ),
  //     ),
  //   );
  // }

  $context->condition_mode = 0;
  $context->table = "context";
  $context->type = "Normal";
  $context->export_type = 1;

  context_save($context);
  cache_clear_all();

  drupal_set_message("An active fellowship context was created for you. " . l(t("Edit it here") . " »", "admin/structure/context/list/" . $context_name . "/edit"));

}

//  ////////////////////////////////////////////////////////////////////////////
//  GETTERS ////////////////////////////////////////////////////////////////////
//  ////////////////////////////////////////////////////////////////////////////


/**
 * Gets the fellowship menu.
 * @return array menu information
 */
function _stanford_vpge_fellowships_get_fellowship_menu() {
  $menu = menu_load(VPGE_FELLOWSHIPS_MENU_NAME);
  return $menu;
}

/**
 * Returns the active fellowship node object or false if none.
 * @return [object] [the active fellowship node or false]
 */
function _get_active_fellowship() {

  // Start off with the easy one. If we are on a fellowship node return it.
  global $node;
  if ($node->type == "fellowship_funding") {
    return $node;
  }

  // Next run by path.
  $current_path = current_path();
  $menu = _stanford_vpge_fellowships_get_fellowship_menu();
  $menu_item = menu_get_item($current_path);
  $menu_tree_page = menu_tree_page_data($menu['menu_name']);

  // Loop through the trail and see where we are at.
  foreach ($menu_tree_page as $index => $item) {
    if ($item['link']['link_path'] == $current_path) {
      // FOUND IT.
      return node_load(str_replace('node/', '', $item['link']['link_path']));
    }
    if (!empty($item['below'])) {
      $found = _stanford_vpge_fellowships_check_below_links($item['below']);
      if ($found) {
        return node_load(str_replace('node/', '', $item['link']['link_path']));
      }
    }
  }

  return FALSE;
}

/**
 * Recursive loop checking.
 * @param  [type] $items   [description]
 * @param  [type] $context [description]
 * @return [type]          [description]
 */
function _stanford_vpge_fellowships_check_below_links($items) {
  foreach ($items as $item) {
    if ($item['link']['link_path'] == current_path()) {
      return $item;
    }
    if (!empty($item['below'])) {
      $found = _stanford_vpge_fellowships_check_below_links($item['below']);
      if ($found) {
        return $found;
      }
    }
  }
  return FALSE;
}



//  ////////////////////////////////////////////////////////////////////////////
//  CONTEXT PLUGINS //
//  ////////////////////////////////////////////////////////////////////////////

/**
 * We want to allow users to place any type of content or link into the
 * fellowships and funding menu. When they do that we want to maintain the
 * fellowships context that the item belongs to. To do this we will harness
 * the functionality of context.
 */

/**
 * Implement `hook_context_plugins()` to define your plugins, classes, and class
 * hierarchy.
 * @return $plugins
 */
function stanford_vpge_fellowships_context_plugins() {
  $plugins = array();
  $plugins['context_condition_active_fellowships'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'stanford_vpge_fellowships') . '/plugins',
      'file' => 'context_condition_active_fellowships.inc',
      'class' => 'context_condition_active_fellowships',
      'parent' => 'context_condition',
    ),
  );
  $plugins['context_reaction_active_fellowships'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'stanford_vpge_fellowships') . '/plugins',
      'file' => 'context_reaction_active_fellowships.inc',
      'class' => 'context_reaction_active_fellowships',
      'parent' => 'context_reaction',
    ),
  );
  return $plugins;
}

/**
 * Implement `hook_context_registry()` to define your conditions and/or
 * reactions and map them to plugins.
 * @return array
 */
function stanford_vpge_fellowships_context_registry() {
  return array(
    'conditions' => array(
      'active_fellowships' => array(
        'title' => t('Active Fellowships'),
        'description' => t('By Selecting the Any Fellowship Section this context will evaluate all paths to see if the content being viewed is in the Fellowships & Funding menu tree. If it is then it will trigger the reactions. You can also assert if a path item is in a specific fellowship by selecting the name of the fellowship.'),
        'plugin' => 'context_condition_active_fellowships',
      ),
    ),
    'reactions' => array(
      'active_fellowships' => array(
        'title' => t('Active Fellowships'),
        'description' => t('Set the active fellowship section.'),
        'plugin' => 'context_reaction_active_fellowships',
      ),
    ),
  );
}

/**
 * Execute Context active fellowship conditions
 *
 * Allows modules to hook into Context's hook_page_build to execute their
 * conditions at an appropriate time before the firing of reactions.
 */
function stanford_vpge_fellowships_context_page_condition() {

  $plugin = context_get_plugin('condition', 'active_fellowships');
  if ($plugin) {
    $plugin->execute();
  }

}

/**
 * Implements hook_context_page_reaction().
 */
function stanford_vpge_fellowships_context_page_reaction() {

  if ($plugin = context_get_plugin('reaction', 'active_fellowships')) {
    $plugin->execute();
  }

}

// /////////////////////////////////////////////////////////////////////////////
// // END CONTEXTS /////////////////////////////////////////////////////////////
// /////////////////////////////////////////////////////////////////////////////



